  subroutine dynamic_fc
!
!  Master routine for generating second derivatives for phonons
!  when storing as separate cell images for later phasing.
!  On diagonal block elements (i,i) for element i can no longer be
!  generated by summing off diagonals. Therefore these elements
!  are retained from the normal second derivative matrix and
!  added in afterwards in phonon.
!
!  10/14 Created from dynamic
!   2/15 Criterion for calling getBOcharge changed by adding nboQ0
!   4/17 Modified to handle distributed memory second derivatives
!
!  Conditions of use:
!
!  GULP is available free of charge to academic institutions
!  and non-commerical establishments only. Copies should be
!  obtained from the author only and should not be distributed
!  in any form by the user to a third party without the express
!  permission of the author. This notice applies to all parts
!  of the program, except any library routines which are
!  distributed with the code for completeness. All rights for
!  such routines remain with the original distributor.
!
!  No claim is made that this program is free from errors and
!  no liability will be accepted for any loss or damage that
!  may result. The user is responsible for checking the validity
!  of their results.
!
!  Copyright Curtin University 2017
!
!  Julian Gale, CIC, Curtin University, July 2017
!
  use bondorderdata, only : nbopot, nboQ, nboQ0
  use control
  use current
  use derivatives
  use eam,           only : lMEAMden
  use four
  use parallel
  use six
  use sutton
  use m_three
  implicit none
!
!  Local variables
!
  integer(i4)                               :: maxlim
  integer(i4)                               :: maxlimloc
  integer(i4)                               :: mint
  integer(i4)                               :: mintloc
  real(dp)                                  :: eatom
!**********************************************
!  EEM/QEq calculation of charge derivatives  *
!**********************************************
  if (leem) then
    call dcharge(.false.,.true.,.false.)
  endif
!*************************************************
!  Bond Order calculation of charge derivatives  *
!*************************************************
  if ((nboQ+nboQ0).gt.0) then
    call getBOcharge(.true.,.true.)
  endif
!****************************
!  Zero second derivatives  *
!****************************
  mint = 3*numat
  mintloc = 3*natomsonnode
  maxlim = mint
  maxlimloc = mintloc
  if (nbsmat.gt.0) then 
    maxlim = maxlim + numat
    maxlimloc = maxlimloc + natomsonnode
  endif
  if (maxlimloc.gt.maxd2u) then
    maxd2u = maxlimloc
    call changemaxd2
  endif
  if (maxlim.gt.maxd2) then
    maxd2 = maxlim
    call changemaxd2
  endif
!
  derv2(1:maxlim,1:maxlimloc) = 0.0_dp
  d2cell(1:maxlim,1:maxlimloc,1:nd2cells) = 0.0_dp
!*************************
!  Real space component  *
!*************************
  if (nprocs.gt.1) then
    call realfcd
  else
    call realfc
  endif
!**********************************
!  Bond order charge self-energy  *
!**********************************
  if (nboQ0.gt.0) then
    call BOselffc
  endif
!*************************
!  Three-body component  *
!*************************
  if (nthb.gt.0) then
    if (nprocs.gt.1) then
      call threefcd
    else
      call threefc
    endif
  endif
!************************
!  Four-body component  *
!************************
  if (nfor.gt.0) then
    if (nprocs.gt.1) then
      call fourfcd
    else
      call fourfc
    endif
  endif
!***********************
!  Six-body component  *
!***********************
  if (nsix.gt.0) then
    if (nprocs.gt.1) then
      call sixfcd
    else
      call sixfc
    endif
  endif
!************************
!  Many-body component  *
!************************
  if (lsuttonc) then
    if (lMEAMden) then
      eatom = 0.0_dp
      call density3(eatom)
    endif
    if (nprocs.gt.1) then
      call manyfcd
    else
      call manyfc
    endif
  endif
!**********************
!  Brenner potential  *
!**********************
  if (lbrenner) then
    if (nprocs.gt.1) then
      call brennerfcd
    else
      call brennerfc
    endif
  endif
!************************
!  Bondorder potential  *
!************************
  if (nbopot.gt.0) then
    if (nprocs.gt.1) then
      call bondorderfcd
    else
      call bondorderfc
    endif
  endif
!
  return
  end
