# Problem 1 {-}

```{r}
# Structure parameters
struc = "MgO"
nat = 2
# Data parameters
filepath='p1/data'
data <- read.table(file = filepath,header = TRUE,comment.char = "#")
data <- data[order(data$Ecutwf),]
data$Energy <- data$Energy/2
# Packages
library(ggplot2)

# Data processing
folder <- basename(getwd())
ref <- subset(data,Ecutwf==200 & Kmesh==2)
```

```{r P1_EcutEnergy, echo=FALSE, fig.cap= "Energy convergence for R phase with respect to Ecutwf"}
# Energy plot ****************************************************
plot(data$Ecutwf, abs(data$Energy), pch = 3, col="red"   , type="b",
     main="Energy convergence",
     ylim=range(abs(data$Energy[3:16])),
     xlab="Ecutwf [Ry]",
     ylab="Absolute Energy [Ry/Atom]")
lines(range(data$Ecutwf),rep(max(abs(data$Energy)),2)-0.36, col="blue", lty=2)
legend("right",legend = c("Energy","Treshold"),col=c("red","blue"),pch=c(3,NA),lty=c(1,2))
text(x=mean(data$Ecutwf), y=mean(abs(data$Energy)),"Ecutrho/Ecutwf=4")
grid()
```
### Problem 2 {-}

```{r}
# Structure parameters
struc = "MgO"
nat = 2
# Data parameters
filepath='p2/data'
data <- read.table(file = filepath,header = TRUE,comment.char = "#")
data <- data[order(data$Ecutwf),]
data$MgF <- data$F1*sqrt(3)
# Packages
library(ggplot2)

# Data processing
folder <- basename(getwd())
ref <- subset(data,Ecutwf==200)
```

```{r P2_EcutForce, echo=FALSE, fig.cap= "Energy convergence for R phase with respect to Ecutwf"}
# Force plot ****************************************************
err=0.35e-3
plot(data$Ecutwf, abs(data$MgF), pch = 3, col="red"   , type="b",
     main="Force convergence",
     ylim=2*c(-err,+err)+abs(ref$MgF),
     xlab="Ecutwf [Ry]",
     ylab="Force acting on Mg atom [Ry/Borh]")
lines(range(data$Ecutwf,2),abs(rep(ref$MgF,2))-err, col="blue", lty=2)
lines(range(data$Ecutwf,2),abs(rep(ref$MgF,2))+err, col="blue", lty=2)
legend("topright",legend = c("Force (Module)","Treshold"),col=c("red","blue"),pch=c(3,NA),lty=c(1,2))
text(x=40, y=0.14, "Ecutrho/Ecutwf=4")
grid()
```

### Problem 3 {-}

```{r}
# Structure parameters
struc = "MgO"
nat = 2
# Data parameters
filepath='p3/data'
data <- read.table(file = filepath,header = TRUE,comment.char = "#")
data <- data[order(data$Kmesh),]
data$Energy <- data$Energy/2
# Packages
library(ggplot2)

# Data processing
folder <- basename(getwd())
ref <- subset(data,Kmesh==8)
```

```{r P3_KmeshEnergy, echo=FALSE, fig.cap= "Energy convergence for R phase with respect to Ecutwf"}
# Force plot ****************************************************
plot(data$Kmesh, abs(data$Energy), pch = 3, col="red"   , type="b",
     main="Energy convergence",
     ylim=range(abs(data$Energy)),
     xlab="Kmesh",
     ylab="Absolute Energy [Ry/Atom]")
lines(range(data$Kmesh),rep(abs(ref$Energy),2)-0.36, col="blue", lty=2)
legend("right",legend = c("Energy","Treshold"),col=c("red","blue"),pch=c(3,NA),lty=c(1,2))
text(x=40, y=0.14, "Ecutrho/Ecutwf=4")
grid()
```

### Problem 4 {-}

```{r}
# Structure parameters
struc = "MgO"
nat = 2
# Data parameters
filepath='p4/data'
data <- read.table(file = filepath,header = TRUE,comment.char = "#")
data <- data[order(data$Ecutwf),]
data$MgF <- data$F1*sqrt(3)
# Packages
library(ggplot2)

# Data processing
folder <- basename(getwd())
ref <- subset(data,Kmesh==8)
```

```{r P4_KmeshForce, echo=FALSE, fig.cap= "Energy convergence for R phase with respect to Ecutwf"}
# Force plot ****************************************************
err=0.35e-3
plot(data$Kmesh, abs(data$MgF), pch = 3, col="red"   , type="b",
     main="Force convergence",
     ylim=2*c(-err,+err)+abs(ref$MgF),
     xlab="Kmesh",
     ylab="Force acting on Mg atom [Ry/Borh]")
lines(range(data$Kmesh,2),abs(rep(ref$MgF,2))-err, col="blue", lty=2)
lines(range(data$Kmesh,2),abs(rep(ref$MgF,2))+err, col="blue", lty=2)
legend("topright",legend = c("Force (Module)","Treshold"),col=c("red","blue"),pch=c(3,NA),lty=c(1,2))
text(x=40, y=0.14, "Ecutrho/Ecutwf=4")
grid()
```

### Problem 5 {-}


```{r}
# Structure parameters
struc = "MgO"
nat = 2
# Data parameters
filepath='p5/data'
data <- read.table(file = filepath,header = TRUE,comment.char = "#",na.strings = "")
data <- data[order(data$Ecutwf),]
data$Energy <- data$Energy/2
# Packages
library(ggplot2)
alat1 <- subset(data,Alat==8.01)
alat2 <- subset(data,Alat==7.97)

# Data processing
folder <- basename(getwd())
```

```{r P3_KmeshEnergy, echo=FALSE, fig.cap= "Energy convergence for R phase with respect to Ecutwf"}
# Force plot ****************************************************
plot(alat1$Ecutwf, alat1$DEnergy, pch = 2, col="red"   , type="b", lty=2,
     main="Energy convergence",
     ylim=range(alat1$DEnergy[3:16]),
     xlab="Ecutwf [Ry]",
     ylab="Relative Energy [Ry/Atom]")
lines(alat2$Ecutwf, alat2$DEnergy, pch = 6, col="chartreuse", type="b", lty=2)
lines(range(data$Ecutwf),rep(0,2)+0.36, col="blue", lty=2)
legend("right",legend = c("a=8.01 [Bohr]","a=7.97 [Bohr]"),col=c("red","chartreuse"),pch=c(2,6),lty=c(2,2))
text(x=40, y=20, "Ecutrho/Ecutwf=4")
grid()
```


The minimum of the fit function is at r = `r cat("put here some r code")` Angstroms.
